/**
 * Supabase Database Types
 *
 * This file should be auto-generated by running:
 *   npx supabase gen types typescript --project-id <your-project-id> > src/types/database.ts
 *
 * Or if you have the Supabase CLI installed:
 *   supabase gen types typescript --linked > src/types/database.ts
 *
 * For now, we define types manually based on our schema.
 * Replace this file with auto-generated types once you set up the CLI.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      journeys: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          destination: string | null;
          emoji: string | null;
          status: 'active' | 'completed';
          unlock_date: string;
          shared_with: string[] | null;
          cover_image_url: string | null;
          cover_image_attribution: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          destination?: string | null;
          emoji?: string | null;
          status?: 'active' | 'completed';
          unlock_date: string;
          shared_with?: string[] | null;
          cover_image_url?: string | null;
          cover_image_attribution?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          destination?: string | null;
          emoji?: string | null;
          status?: 'active' | 'completed';
          unlock_date?: string;
          shared_with?: string[] | null;
          cover_image_url?: string | null;
          cover_image_attribution?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'journeys_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      memories: {
        Row: {
          id: string;
          journey_id: string;
          type: 'photo' | 'video' | 'audio' | 'text';
          url: string | null;
          note: string | null;
          duration: number | null;
          latitude: number | null;
          longitude: number | null;
          location_name: string | null;
          weather: Json | null;
          tags: string[] | null;
          filter: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          journey_id: string;
          type: 'photo' | 'video' | 'audio' | 'text';
          url?: string | null;
          note?: string | null;
          duration?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          location_name?: string | null;
          weather?: Json | null;
          tags?: string[] | null;
          filter?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          journey_id?: string;
          type?: 'photo' | 'video' | 'audio' | 'text';
          url?: string | null;
          note?: string | null;
          duration?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          location_name?: string | null;
          weather?: Json | null;
          tags?: string[] | null;
          filter?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'memories_journey_id_fkey';
            columns: ['journey_id'];
            referencedRelation: 'journeys';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey';
            columns: ['id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      journey_status: 'active' | 'completed';
      memory_type: 'photo' | 'video' | 'audio' | 'text';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// =============================================================================
// HELPER TYPES
// =============================================================================

/** Type alias for a table row */
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

/** Type alias for inserting into a table */
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

/** Type alias for updating a table */
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

/** Type alias for enums */
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// =============================================================================
// CONVENIENCE EXPORTS
// =============================================================================

export type JourneyRow = Tables<'journeys'>;
export type JourneyInsert = TablesInsert<'journeys'>;
export type JourneyUpdate = TablesUpdate<'journeys'>;

export type MemoryRow = Tables<'memories'>;
export type MemoryInsert = TablesInsert<'memories'>;
export type MemoryUpdate = TablesUpdate<'memories'>;

export type ProfileRow = Tables<'profiles'>;
export type ProfileInsert = TablesInsert<'profiles'>;
export type ProfileUpdate = TablesUpdate<'profiles'>;

export type JourneyStatus = Enums<'journey_status'>;
export type MemoryType = Enums<'memory_type'>;

